# Generated by Django 4.1.1 on 2023-08-07 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='director_general',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='laboratorio_asignado', to='laboratorio.directorgeneral'),
        ),
        migrations.AlterField(
            model_name='directorgeneral',
            name='laboratorio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.laboratorio'),
        ),
    ]