# Generated by Django 4.1.1 on 2023-08-07 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_alter_laboratorio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre']},
        ),
    ]